### ISSUE TITLE
Volume Mounting

### ISSUE THREAD

**Issue by SpontaneousDuck** [ml-tooling/ml-hub#13]
**Feature description:**
The ability to mount system folders in to spawned containers on the DockerSpawner. Either a predefined list of mounts or a line to specify in the spawner configuration interface.

**Problem and motivation:**
It would be extremely useful for us to be able to mount external volumes in to spawned containers. Our system has multiple nfs volumes mounted on the the local filesystem where our data is stored. We would like to be able to mount those in to spawned containers. This is useful for the case when you have data you want to work on that is stored somewhere else on your system.

**Is this something you're interested in working on?**
Maybe, not much free time available currently

**Comment by christophelec** [comment]
Would using this config https://jupyterhub-dockerspawner.readthedocs.io/en/latest/data-persistence.html#volume-mapping in your jupyter_user_config.py fix you use case ?

A similar config on the KubeSpawner works on K8S

**Comment by SpontaneousDuck** [comment]
Yes! Indeed it would. Thanks for the help
