### ISSUE TITLE
Compile to ARM64 arch

### ISSUE THREAD

**Issue by armandleopold** [ml-tooling/ml-hub#15]
**Feature description:**
Compile docker images for ARM64 arch

**Problem and motivation:**

I want to do machine learning on my raspberry cluster

**Is this something you're interested in working on?**

Yes why not =)

**Comment by armandleopold** [comment]
Up

**Comment by raethlein** [comment]
Hey @armandleopold,

I think learning more about how to compile Docker images for ARM64 would also be interesting for us! Someone asked [on Gitter](https://gitter.im/ml-tooling/ml-workspace) a similar question with regards to Apple's M1 Macbook and the [ml-workspace image](https://github.com/ml-tooling/ml-workspace). I think we won't be able to spend a lot of time on this issue ourselves right now but if you gain any learnings you can share here, that would be great!

**Comment by armandleopold** [comment]
Sorry @raethlein but i don't have time for that currently =S.
