### ISSUE TITLE
Using newer version of vs code server

### ISSUE THREAD

**Issue by stamerf** [ml-tooling/ml-hub#24]
Thank you very much for this nice work! I am very impressed!
I just have a little wish: Could you change the vs code server version to the newest? Somehow I can't update the version in the container via the gui, it throws an error. The easiest solution would be to use the neweset vs code server version. 

Unfortunately I don't have the skill to fix this inside your code myself. But I guess it would be one line of code for you.

Thank you and best regards.

**Comment by raethlein** [comment]
Hey @stamerf, thanks a lot for the appreciation :) We will update VS Code in the next version of [ml-workspace](https://github.com/ml-tooling/ml-workspace).
In the meantime, you can execute the code in the bottom in your running workspace instance.
To do so, go to your workspace instance > New (top-right corner below "Open Tool") > Terminal
Paste the following lines and press enter (although this code should not break anything, think about backing up your data / code so that you can restart a fresh instance just in case):

```
# Stop the code server process
supervisorctl stop vscode

# Replace the version in our installer script
sed -i 's/VS_CODE_VERSION=3.8.0/VS_CODE_VERSION=3.9.1/g' /resources/tools/vs-code-server.sh

# Remove the executable link file
rm /usr/bin/code-server

# Remove the current code-server version
yarn global remove code-server

# Install the new version
/resources/tools/vs-code-server.sh

# Start the code server process again
supervisorctl start vscode
```

I have tested it with the newest workspace image `mltooling/ml-workspace:0.12.1`. Though I have not tested it in conjunction with ml-hub or older versions of ml-workspace.

I hope this helps! If you have more feedback, we would love to hear about it.

**Comment by stamerf** [comment]
Thank you very much for the fast response, I appreciate it a lot. Unfortunately, the docker image used when following your quick install guide on the homepage for mlhub is using code-server Version: 1.38.1 @ downloadlink https://github.com/cdr/code-server/releases/download/2.1478-vsc1.38.1/code-server2.1478-vsc1.38.1-linux-x86_64.tar.gz . The update ist not as easy as you described it. I tried fixing it, but the new version is running quite differently. E.g. multiple flags are not valid anymore like --allow-http or --no-auth. Therefore I rolled back to the old version. Maybe the Image from docker hub is just too old? I don't know actually. If it would be the case, building the image myself would fix it I guess.

**Comment by raethlein** [comment]
Ah yes, ML Hub uses by default a quite old workspace image. You can create a file locally called `jupyterhub_user_config.py` with the following content:

```
c.Spawner.image = "mltooling/ml-workspace:0.12.1"
```

and pass it to the docker run command via `-v <path_to_your_jupyterhub_user_config.py>:/resources/jupyterhub_user_config.py`, for example like this:

```
docker run \                    
    -p 8080 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v jupyterhub_data:/data \
    -v $(pwd)/jupyterhub_user_config.py:/resources/jupyterhub_user_config.py \
    mltooling/ml-hub:latest
   
# Note: $(pwd) resolves to the current directory, e.g. /Users/ben/Documents -> /Users/ben/Documents/jupyterhub_user_config.py)
```

With this config, the default workspace image used by hub is `mltooling/ml-workspace:0.12.1`.
You have to remove the current hub container before you can start the new one via `docker stop mlhub &&  docker rm mlhub` (in case your container's name is `mlhub`)

**Comment by stamerf** [comment]
Hi, thank you. At the same time I did this and tried to rebuild from the dockerfile. I got multiple bugs:

1. When using original Dockerfile I got an error from the pip command when installing the crypto package. After googling it seems like there is a bug with old pip version.
-> I fixed that by adding "RUN pip3 install --user --upgrade pip" after installting python3-dev 

2. Then I got an error when calling the signup page of jupyterhub. There is an error with jupyterhub 1.3 and tornado (see https://github.com/jupyterhub/nativeauthenticator/issues/130)
-> I fixed that by changing this line "python3 -m pip install --no-cache -I jupyterhub==1.2.1 " using a previous build of jupyterhub. 

Hope this helps. 

But now vs code is not working anymore...

**Comment by raethlein** [comment]
Thanks for the details. It sounds like building a new version of the image would take a little bit more time. So, I suggest to use the current hub version and use the approach I described before for now :)

**Comment by stamerf** [comment]
Unfortunately, that way the same error occurs. There is only a loading screen for vscode. 
In terminal the supervisorctl says: vscode FATAL can't find command '/usr/local/bin/code-server'

I guess this is rather becoming a bug report than a feature request =D

**Comment by raethlein** [comment]
Since it worked for me when I tested it locally, maybe it helps if you delete the started workspace container and start a fresh one from ML Hub (with the user config mounted) and try out the steps again.

**Comment by stamerf** [comment]
Hi, I managed to fix it now! The problem was a zombie container still running (something like ws-mlhub-admin) which I didn't see at first. It is neccessary to delete it by hand completly because otherwise mlhub is picking it up even if you specified to use a new image-version. That solved it for me now. Thank you again for the support. This is such a great project! I love it!

**Comment by raethlein** [comment]
Great, really glad to hear that it worked out! And thanks for the kind words :)
