### ISSUE TITLE
Upstream Error when running via docker

### ISSUE THREAD

**Issue by gurjmatharu** [ml-tooling/ml-hub#3]
Hi,

Thanks for this awesome tooling-set!  Really cool.
I'm running into an issue trying to launch ml-hub via docker.

**Expected behaviour:**

ML-Hub launches and is able to accept connections.

**Steps to reproduce the issue:**

From https://github.com/ml-tooling/ml-workspace#multi-user-setup

Run the following docker command:
```
docker run -p 8080:8080 --name mlhub -v /var/run/docker.sock:/var/run/docker.sock mltooling/ml-hub:latest
```

**Technical details:**

- Hub version: latest 
- Docker version Docker version 19.03.5, build 633a0ea
- Host Machine OS (Windows/Linux/Mac): Mac
- Command used to start the hub: `docker run -p 8080:8080 --name mlhub -v /var/run/docker.sock:/var/run/docker.sock mltooling/ml-hub:latest`
- Browser (Chrome/Firefox/Safari): Chrome

**Possible Fix:**
N/A

**Additional context:**

Output from docker:
```
Start JupyterHub
2019/11/29 23:12:28 [error] 736#0: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "localhost:8080"
2019/11/29 23:12:28 [warn] 736#0: *4 upstream server temporarily disabled while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "localhost:8080"
2019/11/29 23:12:28 [error] 736#0: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "localhost:8080"
2019/11/29 23:12:28 [warn] 736#0: *4 upstream server temporarily disabled while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "localhost:8080"
2019/11/29 23:12:28 [error] 736#0: *4 open() "/resources/5xx.html" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "localhost:8080"```

**Comment by raethlein** [comment]
Hey @gurjmatharu,

thanks for the feedback!

Could you try the following please:

```
docker rm mlhub;
docker run \
    -d \
    -p 8080:8080 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    mltooling/ml-hub:0.1.10
```

It's always best to use a dedicated version instead of `latest`.
Further, unfortunately, the hub documentation you linked is not up-to-date, so for the newest documentation, check the [mlhub page](https://github.com/ml-tooling/ml-hub). Sorry for the inconvenience!

**Comment by gurjmatharu** [comment]
@raethlein 

Works great!

Thank you!
